In [1]:
import numpy as np

print("NumPy imported successfully!")

NumPy imported successfully!


In [2]:
random_integers = np.random.randint(1, 101, size=10)

print("Random Integers:")
print(random_integers)

Random Integers:
[21 66 70 44 72  4 37 67  4  2]


In [3]:
random_floats = np.random.random(10)

print("Random Floating-Point Numbers:")
print(random_floats)

Random Floating-Point Numbers:
[0.80324076 0.20162716 0.97523715 0.04709343 0.08214798 0.49391418
 0.7610079  0.73169498 0.40812346 0.18439628]


In [4]:
students = np.array([
    "Student_1", "Student_2", "Student_3", "Student_4", "Student_5",
    "Student_6", "Student_7", "Student_8", "Student_9", "Student_10"
])

sample = np.random.choice(students, size=5, replace=False)

print("Original Array:")
print(students)

print("\nRandom Sample:")
print(sample)

Original Array:
['Student_1' 'Student_2' 'Student_3' 'Student_4' 'Student_5' 'Student_6'
 'Student_7' 'Student_8' 'Student_9' 'Student_10']

Random Sample:
['Student_3' 'Student_6' 'Student_5' 'Student_9' 'Student_2']


In [5]:
np.random.seed(42)

marks = np.random.randint(40, 101, size=10)

student_data = {
    "Student": np.arange(1, 11),
    "Marks": marks
}

print("Simulated Student Marks:")
print(student_data)

Simulated Student Marks:
{'Student': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 'Marks': array([ 78,  91,  68,  54,  82,  47, 100,  60,  78,  97])}


In [6]:
np.random.seed(42)
result_1 = np.random.randint(1, 101, size=5)

np.random.seed(42)
result_2 = np.random.randint(1, 101, size=5)

print("First Result:")
print(result_1)

print("\nSecond Result:")
print(result_2)

print("\nAre both results identical?", np.array_equal(result_1, result_2))

First Result:
[52 93 15 72 61]

Second Result:
[52 93 15 72 61]

Are both results identical? True


## Interpretation

NumPy provides several functions for generating random data, including random integers, floating-point numbers, and random samples from arrays.

A random seed was used to make the generated results reproducible. When the same seed is used with the same random-generation process, the same sequence of values is produced.

Random sampling is useful in data science for simulations, experimentation, sampling datasets, testing algorithms, and creating synthetic data.

Reproducibility is important because it allows other researchers or developers to obtain the same results and verify an experiment.

## Interview Questions

### 1. Why are random numbers useful in data science?

Random numbers are useful for sampling, simulations, experiments, creating synthetic datasets, and testing machine learning algorithms.

### 2. What is a random seed?

A random seed is an initial value used by a random number generator. Using the same seed produces the same sequence of random values.

### 3. Why is reproducibility important?

Reproducibility ensures that an experiment can be repeated and produce the same results. It helps with debugging, verification, research, and reliable data science experiments.